[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "NODE_ENV=production npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicy = "on-failure"
restartPolicyMaxRetries = 10

[phases.setup]
nixPkgs = ["nodejs", "postgresql", "pkg-config"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]

[phases.start]
cmds = ["NODE_ENV=production npm start"]

[health]
path = "/api/health"
timeout = 300
interval = 30
retries = 5 